name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Decode and write .env
      env:
        ENV_FILE_BASE64: ${{secrets.ENV_FILE_BASE64}}
      run: |
        echo "$ENV_FILE_BASE64" | base64 -d > .env
    
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kristianrpo30/tonali:latest
      
    - name: Docker Push
      run: docker push kristianrpo30/tonali
